### ISSUE TITLE
Viability of a JSIL port

### ISSUE THREAD

**Issue by Happy-Ferret** [scemino/nscumm#7]
I don't have any Windows computer currently that I could compile nscumm and JSIL on, however I'm genuinely interested in the viability of such a port. 

Has it ever been attempted before to compile nscumm with JSIL, providing a universal web application that can be run on most devices (including the browser)?

**Comment by scemino** [comment]
As far as I know no.
Actually, these days I'm focused on the Universal Windows Platform, for the Windows Phone/Desktop users.
But anyone can try this kind of port or maybe JSIL is available on Linux or MacOs.
